config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :photos do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'top' => 'homes#top'
  get 'menu' => 'homes#menu'
  get 'access' => 'homes#access'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :photo
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @photo = Photo.find(params[:photo_id])
    favorite = current_user.favorites.new(photo_id: @photo.id)
    favorite.save
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    favorite = current_user.favorites.find_by(photo_id: @photo.id)
    favorite.destroy
  end
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if @photo.favorited_by?(current_user) %>
<li>
  <%= link_to photo_favorites_path(@photo), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= @photo.favorites.count %> 
  <% end %>
</li>
<% else %>
<li>
  <%= link_to photo_favorites_path(@photo), method: :post, remote: true do %>
    <i class="fa fa-heart-o core" aria-hidden="true" style="color: gray;"></i>
    <%= @photo.favorites.count %>
  <% end %>
</li>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @photo.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {photo: @photo}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @photo.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {photo: @photo}) %>");