config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :photos do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'top' => 'homes#top'
  get 'menu' => 'homes#menu'
  get 'access' => 'homes#access'
end

app/models/photo.rb
class Photo < ApplicationRecord
  
  validates :image, :title, :body, presence: true
  
  belongs_to :user
  attachment :image
  has_many :comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(search)
    if search
      Photo.where(['title LIKE ?', "%#{search}%"])
    else
      Photo.all
    end 
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @photos = Photo.search(params[:search])
    #検索対象を格納、条件分岐はモデルに記述
  end

  def show
    @photo = Photo.find(params[:id])
    @user = @photo.user
    @comment = Comment.new
    @comments = @photo.comments
  end

  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      flash[:notice] = '投稿しました。' 
      redirect_to photos_path
    else
      render 'photos/new'
    end
  end
  
  def destroy
     @photo = Photo.find(params[:id])
     @photo.destroy
     flash[:notice] = '投稿を削除しました。' 
     redirect_to photos_path
  end  
  
  #投稿機能用ストロングパラメーター
  private
  def photo_params
    params.require(:photo).permit(:image, :title, :body)
  end
  
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/index.html.erb
<article class="menu-base">
  <div class="base-title">
    <h2>SHARE</h2>
    <p>島を愛するみんなに写真をシェアしてみましょう</p>
  </div>
</article>

<% if flash[:notice] %>
  <div class="notion_message">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<br>
<%= form_tag(photos_path, :method => 'get') do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag '投稿を検索', :title => nil %>
<% end %>

<div class="plus_button">
  <%= link_to image_tag("icon_001523_128.png"), new_photo_path %>
</div>

<div class="section">
  <div class="flexbox">
    <% @photos.each do |photo| %>
    <ul>
        <li>
          <div class="photo_tile">
            <%= link_to photo_path(photo.id) do %>
            <%= attachment_image_tag photo, :image, size: "250x250", format: 'jpeg' %>
            <div class="mask">
              <div class="caption">
                <%= photo.title %>
                <br>
                <br>
                <i class="fa fa-commenting-o"></i> 
                <%= photo.comments.count %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= photo.favorites.count %>                 
              </div>
            </div>
            <% end %>
          </div>  
        </li>
    </ul>
    <% end %> 
  </div>
</div>

app/views/photos/new.html.erb
<article class="menu-base">
  <div class="base-title">
    <h2>POST PHOTO</h2>
    <p>島の写真を投稿してみましょう！</p>
  </div>
</article>

<% if @photo.errors.any? %>
  <div>
    <ul style="color: red">
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <div class="back_image_2">
    <div class="container">
      <div class="signup_tile">
        <h2>写真投稿</h2>
        <%= form_with model:@photo, local:true do |f| %>
        <%= f.attachment_field :image %>
        <br>
        <br>
        <%= f.label :タイトル %> 
        <%= f.text_field :title, size: "25x1" %>
        <br>
        <br>
        <%= f.label :コメント %> 
        <%= f.text_area :body, size: "27x10", placeholder:"コメントを記入" %>
        <br>
        <br>
        <br>
        <%= f.submit '投稿', :class => 'submit_button' %>
        <% end %>  
      </div>
    </div>
  </div>

app/views/photos/show.html.erb
<article class="menu-base">
  <div class="base-title">
    <h2><%= @photo.title %></h2>
    <p>投稿者： <%= link_to @user.name, user_path(@user) %> さん</p></p>
  </div>
</article>

<% if flash[:notice] %>
  <div class="notion_message">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<div class="post_photo">
  <div class="profile_container_2">
    <div class="out_line_2">
      <div class="profile_box_2">
        <div class="profile_image_2">
          <%= link_to user_path(@user) do %> 
          <%= attachment_image_tag @user, :profile_image, size:"80x80", format: 'png', fallback: "no_image.png" %>
          <% end %>
        </div>
        <div class="profile_body_2">
          <%= link_to @user.name, user_path(@user) %> 
        </div>    
      </div>
    </div>
  </div>  
  
  <div class="image_box">
    <%= attachment_image_tag @photo, :image, size: "500x500", format: 'jpeg' %>
  </div>
  <div class="under_box">
    <div class="comments-count">
      <i class="fa fa-commenting-o"></i> <%= @photo.comments.count %>   
    </div>
    <div id="favorites_buttons_<%= @photo.id %>">
      <%= render partial: 'favorites/favorite', locals: { photo: @photo} %>
    </div>
  </div>
  <div class="comment_body">
    <br>
    <h4><%= @photo.body %></h4>
    <br>
    <br>
    <p><%= @photo.created_at.to_s(:datetime_jp) %> </p>
    <br>
    <br>
    <% if @user == current_user %>
    <div class="delete_button">
      <%= link_to "投稿を削除", photo_path(@photo), method: :delete, data: {confirm: "削除しますか？"}, class:"d-underline" %>
    </div>
    <% end %>
  </div>
</div>
<br>
<br>
<%= form_with model: [@photo, @comment], local: true do |f| %>
  <%= f.text_field :comment, placeholder: "コメントを記入", :size => "60*50" %>
  <%= f.submit '投稿' %>
<% end %>

<% @comments.each do |comment| %>
  <div class="comments-container">
    <div class="comments-user">
      <%= link_to user_path(comment.user) do %>
      <%= attachment_image_tag comment.user, :profile_image, size:"50x50", format: 'png', fallback: "no_image.png" %>
      <% end %>
    </div>
    <div class="comments-body">
      <%= link_to user_path(comment.user) do %>
      <%= comment.user.name %>
      <% end %>
      <br> 
      <%= comment.comment %>
    </div>
    <div class="comments-destroy">
      <% if comment.user == current_user %>
      <%= link_to photo_comment_path(comment.photo.id, comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
      <i class="fa fa-trash-o"></i>
      <% end %>
      <% else %>
      <% end %>    
    </div>
  </div>
<% end %>

<div class="link_buttons">
 <%= link_to "一覧へ戻る", photos_path, class:"d-underline" %>  |  <%= link_to "投稿者の詳細", user_path(@user) %>
</div>